version: "3"

services:
  webserver:
    build: 
      context: "./docker/bin/${PHPVERSION}"
    container_name: "${PHPVERSION}"
    restart: 'always'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    links: 
      - database
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  database:
    build:
      context: "./docker/bin/${DATABASE}"
    container_name: 'database'
    restart: 'always'
    ports:
      - "127.0.0.1:${HOST_MACHINE_POSTGRES_PORT}:5432"
    volumes: 
      - ${POSTGRES_DATA_DIR-./data/POSTGRES}:/var/lib/POSTGRES
      - ${POSTGRES_LOG_DIR-./logs/POSTGRES}:/var/log/POSTGRES
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}